In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression

X, y = make_regression(n_features=5, noise=15, bias=10, random_state=1)


In [5]:
class CustomLinearReg:

    def fit(self, X, y):
        ones = np.ones((X.shape[0], 1))
        X = np.hstack([ones, X])
        ya = y.reshape(-1, 1)
        
        first = np.linalg.inv(np.dot(X.T, X))
        second = np.dot(X.T, ya)
        
        self.theta_ = np.dot(first, second)


    def hypo(self, X):
        return np.dot(X, self.theta_)
    
    def predict(self, X):
        X = np.hstack([np.ones((X.shape[0], 1)), X])
        return self.hypo(X).flatten()

In [6]:
model = CustomLinearReg()
model.fit(X, y)


In [7]:
model.predict(X[:10])

array([  40.67700061,   94.13914173,  119.19311409,  -38.23332827,
       -263.6458621 ,   15.65907497,   63.61668356,   53.70384478,
        -16.57922216,   37.11081015])

In [8]:
y[:10]

array([  43.5171099 ,   57.65141943,  123.08271761,  -43.37373343,
       -247.57689921,    8.53711187,   41.42818339,   51.97005873,
        -20.65603669,   57.77285488])

In [9]:
m2 = LinearRegression()

In [10]:
m2.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
m2.predict(X[:10])

array([  40.67700061,   94.13914173,  119.19311409,  -38.23332827,
       -263.6458621 ,   15.65907497,   63.61668356,   53.70384478,
        -16.57922216,   37.11081015])